// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types/params.proto

//option go_package = "icetrays/types/pb";

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type CpParams struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Cid                  string   `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	NodeData             []byte   `protobuf:"bytes,3,opt,name=nodeData,proto3" json:"nodeData,omitempty"`
	PinNums              uint32   `protobuf:"varint,4,opt,name=pinNums,proto3" json:"pinNums,omitempty"`
	Crust                bool     `protobuf:"varint,5,opt,name=crust,proto3" json:"crust,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CpParams) Reset()         { *m = CpParams{} }
func (m *CpParams) String() string { return proto.CompactTextString(m) }
func (*CpParams) ProtoMessage()    {}
func (*CpParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_09c6ce3c4ab55a73, []int{0}
}
func (m *CpParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CpParams.Unmarshal(m, b)
}
func (m *CpParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CpParams.Marshal(b, m, deterministic)
}
func (m *CpParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CpParams.Merge(m, src)
}
func (m *CpParams) XXX_Size() int {
	return xxx_messageInfo_CpParams.Size(m)
}
func (m *CpParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CpParams.DiscardUnknown(m)
}

var xxx_messageInfo_CpParams proto.InternalMessageInfo

func (m *CpParams) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *CpParams) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *CpParams) GetNodeData() []byte {
	if m != nil {
		return m.NodeData
	}
	return nil
}

func (m *CpParams) GetPinNums() uint32 {
	if m != nil {
		return m.PinNums
	}
	return 0
}

func (m *CpParams) GetCrust() bool {
	if m != nil {
		return m.Crust
	}
	return false
}

type MvParams struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MvParams) Reset()         { *m = MvParams{} }
func (m *MvParams) String() string { return proto.CompactTextString(m) }
func (*MvParams) ProtoMessage()    {}
func (*MvParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_09c6ce3c4ab55a73, []int{1}
}
func (m *MvParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MvParams.Unmarshal(m, b)
}
func (m *MvParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MvParams.Marshal(b, m, deterministic)
}
func (m *MvParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MvParams.Merge(m, src)
}
func (m *MvParams) XXX_Size() int {
	return xxx_messageInfo_MvParams.Size(m)
}
func (m *MvParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MvParams.DiscardUnknown(m)
}

var xxx_messageInfo_MvParams proto.InternalMessageInfo

func (m *MvParams) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *MvParams) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type RmParams struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RmParams) Reset()         { *m = RmParams{} }
func (m *RmParams) String() string { return proto.CompactTextString(m) }
func (*RmParams) ProtoMessage()    {}
func (*RmParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_09c6ce3c4ab55a73, []int{2}
}
func (m *RmParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RmParams.Unmarshal(m, b)
}
func (m *RmParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RmParams.Marshal(b, m, deterministic)
}
func (m *RmParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RmParams.Merge(m, src)
}
func (m *RmParams) XXX_Size() int {
	return xxx_messageInfo_RmParams.Size(m)
}
func (m *RmParams) XXX_DiscardUnknown() {
	xxx_messageInfo_RmParams.DiscardUnknown(m)
}

var xxx_messageInfo_RmParams proto.InternalMessageInfo

func (m *RmParams) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type MkdirParams struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MkdirParams) Reset()         { *m = MkdirParams{} }
func (m *MkdirParams) String() string { return proto.CompactTextString(m) }
func (*MkdirParams) ProtoMessage()    {}
func (*MkdirParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_09c6ce3c4ab55a73, []int{3}
}
func (m *MkdirParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MkdirParams.Unmarshal(m, b)
}
func (m *MkdirParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MkdirParams.Marshal(b, m, deterministic)
}
func (m *MkdirParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MkdirParams.Merge(m, src)
}
func (m *MkdirParams) XXX_Size() int {
	return xxx_messageInfo_MkdirParams.Size(m)
}
func (m *MkdirParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MkdirParams.DiscardUnknown(m)
}

var xxx_messageInfo_MkdirParams proto.InternalMessageInfo

func (m *MkdirParams) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type PinParams struct {
	Cid                  string   `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	PinNums              uint32   `protobuf:"varint,2,opt,name=pinNums,proto3" json:"pinNums,omitempty"`
	Crust                bool     `protobuf:"varint,3,opt,name=crust,proto3" json:"crust,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PinParams) Reset()         { *m = PinParams{} }
func (m *PinParams) String() string { return proto.CompactTextString(m) }
func (*PinParams) ProtoMessage()    {}
func (*PinParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_09c6ce3c4ab55a73, []int{4}
}
func (m *PinParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PinParams.Unmarshal(m, b)
}
func (m *PinParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PinParams.Marshal(b, m, deterministic)
}
func (m *PinParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PinParams.Merge(m, src)
}
func (m *PinParams) XXX_Size() int {
	return xxx_messageInfo_PinParams.Size(m)
}
func (m *PinParams) XXX_DiscardUnknown() {
	xxx_messageInfo_PinParams.DiscardUnknown(m)
}

var xxx_messageInfo_PinParams proto.InternalMessageInfo

func (m *PinParams) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *PinParams) GetPinNums() uint32 {
	if m != nil {
		return m.PinNums
	}
	return 0
}

func (m *PinParams) GetCrust() bool {
	if m != nil {
		return m.Crust
	}
	return false
}

type UnpinParams struct {
	Cid                  string   `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnpinParams) Reset()         { *m = UnpinParams{} }
func (m *UnpinParams) String() string { return proto.CompactTextString(m) }
func (*UnpinParams) ProtoMessage()    {}
func (*UnpinParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_09c6ce3c4ab55a73, []int{5}
}
func (m *UnpinParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnpinParams.Unmarshal(m, b)
}
func (m *UnpinParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnpinParams.Marshal(b, m, deterministic)
}
func (m *UnpinParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnpinParams.Merge(m, src)
}
func (m *UnpinParams) XXX_Size() int {
	return xxx_messageInfo_UnpinParams.Size(m)
}
func (m *UnpinParams) XXX_DiscardUnknown() {
	xxx_messageInfo_UnpinParams.DiscardUnknown(m)
}

var xxx_messageInfo_UnpinParams proto.InternalMessageInfo

func (m *UnpinParams) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func init() {
	proto.RegisterType((*CpParams)(nil), "types.CpParams")
	proto.RegisterType((*MvParams)(nil), "types.MvParams")
	proto.RegisterType((*RmParams)(nil), "types.RmParams")
	proto.RegisterType((*MkdirParams)(nil), "types.MkdirParams")
	proto.RegisterType((*PinParams)(nil), "types.PinParams")
	proto.RegisterType((*UnpinParams)(nil), "types.UnpinParams")
}

func init() { proto.RegisterFile("types/params.proto", fileDescriptor_09c6ce3c4ab55a73) }

var fileDescriptor_09c6ce3c4ab55a73 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xcf, 0x4e, 0x03, 0x21,
	0x18, 0xc4, 0x03, 0xdb, 0x55, 0xfa, 0x55, 0x8d, 0xf9, 0xe2, 0x81, 0x78, 0x50, 0xe4, 0xc4, 0xa9,
	0x1e, 0x7c, 0x04, 0xbd, 0xae, 0x69, 0x48, 0x7c, 0x00, 0xec, 0xd6, 0x48, 0x0c, 0x7f, 0x02, 0xd4,
	0xc4, 0xc4, 0x87, 0x37, 0xc5, 0xad, 0xbb, 0x97, 0xf5, 0x36, 0x33, 0x4c, 0x18, 0x7e, 0x00, 0x96,
	0xaf, 0xb8, 0xcb, 0xf7, 0xd1, 0x24, 0xe3, 0xf2, 0x3a, 0xa6, 0x50, 0x02, 0xb6, 0x35, 0x93, 0xdf,
	0xc0, 0x1e, 0xe3, 0xa6, 0x1e, 0x20, 0xc2, 0x22, 0x9a, 0xf2, 0xce, 0x89, 0x20, 0x6a, 0xa9, 0xab,
	0xc6, 0x4b, 0x68, 0xb6, 0xb6, 0xe7, 0xb4, 0x46, 0x07, 0x89, 0xd7, 0xc0, 0x7c, 0xe8, 0x77, 0x4f,
	0xa6, 0x18, 0xde, 0x08, 0xa2, 0xce, 0xf4, 0x9f, 0x47, 0x0e, 0xa7, 0xd1, 0xfa, 0xe7, 0xbd, 0xcb,
	0x7c, 0x21, 0x88, 0x3a, 0xd7, 0x47, 0x8b, 0x57, 0xd0, 0x6e, 0xd3, 0x3e, 0x17, 0xde, 0x0a, 0xa2,
	0x98, 0xfe, 0x35, 0x72, 0x0d, 0xac, 0xfb, 0x1c, 0xd7, 0xdf, 0x52, 0x70, 0xc7, 0xf5, 0x83, 0xc6,
	0x0b, 0xa0, 0x25, 0x0c, 0xe3, 0xb4, 0x04, 0x79, 0x03, 0x4c, 0xbb, 0xf9, 0xd7, 0xca, 0x3b, 0x58,
	0x75, 0x1f, 0xbd, 0x4d, 0xff, 0x54, 0x3a, 0x58, 0x6e, 0xac, 0x1f, 0x0a, 0x03, 0x1d, 0x19, 0xe9,
	0x26, 0x04, 0x74, 0x86, 0xa0, 0x99, 0x12, 0xdc, 0xc2, 0xea, 0xc5, 0xc7, 0xf9, 0x0b, 0x5f, 0x4f,
	0xea, 0x77, 0x3f, 0xfc, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc7, 0xf1, 0xf8, 0xcf, 0x84, 0x01, 0x00,
	0x00,
}
