// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: consensus/pb/fs.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Instruction_Code int32

const (
	Instruction_CP    Instruction_Code = 0
	Instruction_MV    Instruction_Code = 1
	Instruction_RM    Instruction_Code = 2
	Instruction_MKDIR Instruction_Code = 3
	Instruction_Ls    Instruction_Code = 4
	Instruction_Pin   Instruction_Code = 5
	Instruction_UnPin Instruction_Code = 6
)

var Instruction_Code_name = map[int32]string{
	0: "CP",
	1: "MV",
	2: "RM",
	3: "MKDIR",
	4: "Ls",
	5: "Pin",
	6: "UnPin",
}

var Instruction_Code_value = map[string]int32{
	"CP":    0,
	"MV":    1,
	"RM":    2,
	"MKDIR": 3,
	"Ls":    4,
	"Pin":   5,
	"UnPin": 6,
}

func (x Instruction_Code) String() string {
	return proto.EnumName(Instruction_Code_name, int32(x))
}

func (Instruction_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0e1a8c64c0f1b0bd, []int{3, 0}
}

type Ctx struct {
	Pre                  string   `protobuf:"bytes,1,opt,name=pre,proto3" json:"pre,omitempty"`
	Next                 string   `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	Peer                 string   `protobuf:"bytes,3,opt,name=peer,proto3" json:"peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ctx) Reset()         { *m = Ctx{} }
func (m *Ctx) String() string { return proto.CompactTextString(m) }
func (*Ctx) ProtoMessage()    {}
func (*Ctx) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e1a8c64c0f1b0bd, []int{0}
}
func (m *Ctx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ctx.Unmarshal(m, b)
}
func (m *Ctx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ctx.Marshal(b, m, deterministic)
}
func (m *Ctx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ctx.Merge(m, src)
}
func (m *Ctx) XXX_Size() int {
	return xxx_messageInfo_Ctx.Size(m)
}
func (m *Ctx) XXX_DiscardUnknown() {
	xxx_messageInfo_Ctx.DiscardUnknown(m)
}

var xxx_messageInfo_Ctx proto.InternalMessageInfo

func (m *Ctx) GetPre() string {
	if m != nil {
		return m.Pre
	}
	return ""
}

func (m *Ctx) GetNext() string {
	if m != nil {
		return m.Next
	}
	return ""
}

func (m *Ctx) GetPeer() string {
	if m != nil {
		return m.Peer
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e1a8c64c0f1b0bd, []int{1}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Node struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e1a8c64c0f1b0bd, []int{2}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Instruction struct {
	Code                 Instruction_Code `protobuf:"varint,1,opt,name=code,proto3,enum=pb.Instruction_Code" json:"code,omitempty"`
	Params               []string         `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty"`
	Node                 []byte           `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Instruction) Reset()         { *m = Instruction{} }
func (m *Instruction) String() string { return proto.CompactTextString(m) }
func (*Instruction) ProtoMessage()    {}
func (*Instruction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e1a8c64c0f1b0bd, []int{3}
}
func (m *Instruction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instruction.Unmarshal(m, b)
}
func (m *Instruction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instruction.Marshal(b, m, deterministic)
}
func (m *Instruction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instruction.Merge(m, src)
}
func (m *Instruction) XXX_Size() int {
	return xxx_messageInfo_Instruction.Size(m)
}
func (m *Instruction) XXX_DiscardUnknown() {
	xxx_messageInfo_Instruction.DiscardUnknown(m)
}

var xxx_messageInfo_Instruction proto.InternalMessageInfo

func (m *Instruction) GetCode() Instruction_Code {
	if m != nil {
		return m.Code
	}
	return Instruction_CP
}

func (m *Instruction) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *Instruction) GetNode() []byte {
	if m != nil {
		return m.Node
	}
	return nil
}

type Instructions struct {
	Instruction          []*Instruction `protobuf:"bytes,1,rep,name=instruction,proto3" json:"instruction,omitempty"`
	Ctx                  *Ctx           `protobuf:"bytes,2,opt,name=ctx,proto3" json:"ctx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Instructions) Reset()         { *m = Instructions{} }
func (m *Instructions) String() string { return proto.CompactTextString(m) }
func (*Instructions) ProtoMessage()    {}
func (*Instructions) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e1a8c64c0f1b0bd, []int{4}
}
func (m *Instructions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instructions.Unmarshal(m, b)
}
func (m *Instructions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instructions.Marshal(b, m, deterministic)
}
func (m *Instructions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instructions.Merge(m, src)
}
func (m *Instructions) XXX_Size() int {
	return xxx_messageInfo_Instructions.Size(m)
}
func (m *Instructions) XXX_DiscardUnknown() {
	xxx_messageInfo_Instructions.DiscardUnknown(m)
}

var xxx_messageInfo_Instructions proto.InternalMessageInfo

func (m *Instructions) GetInstruction() []*Instruction {
	if m != nil {
		return m.Instruction
	}
	return nil
}

func (m *Instructions) GetCtx() *Ctx {
	if m != nil {
		return m.Ctx
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.Instruction_Code", Instruction_Code_name, Instruction_Code_value)
	proto.RegisterType((*Ctx)(nil), "pb.Ctx")
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*Node)(nil), "pb.Node")
	proto.RegisterType((*Instruction)(nil), "pb.Instruction")
	proto.RegisterType((*Instructions)(nil), "pb.Instructions")
}

func init() { proto.RegisterFile("consensus/pb/fs.proto", fileDescriptor_0e1a8c64c0f1b0bd) }

var fileDescriptor_0e1a8c64c0f1b0bd = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x41, 0x4f, 0x83, 0x40,
	0x10, 0x85, 0x0b, 0x4b, 0x41, 0x86, 0x5a, 0x71, 0xd5, 0x06, 0x3d, 0x11, 0x2e, 0x72, 0xa2, 0x11,
	0x8f, 0x1e, 0x8c, 0x62, 0x0f, 0x8d, 0xd6, 0x34, 0x9b, 0xe8, 0xa1, 0xf1, 0x52, 0x60, 0x4d, 0x38,
	0x94, 0xdd, 0xb0, 0xdb, 0x04, 0xff, 0x92, 0xbf, 0xd2, 0x0c, 0xad, 0x11, 0x7b, 0xda, 0x37, 0xdf,
	0x3c, 0x86, 0x97, 0x19, 0xb8, 0x28, 0x44, 0xad, 0x78, 0xad, 0xb6, 0x6a, 0x2a, 0xf3, 0xe9, 0xa7,
	0x4a, 0x64, 0x23, 0xb4, 0xa0, 0xa6, 0xcc, 0xa3, 0x7b, 0x20, 0x99, 0x6e, 0xa9, 0x0f, 0x44, 0x36,
	0x3c, 0x30, 0x42, 0x23, 0x76, 0x19, 0x4a, 0x4a, 0xc1, 0xaa, 0x79, 0xab, 0x03, 0xb3, 0x43, 0x9d,
	0x46, 0x26, 0x39, 0x6f, 0x02, 0xb2, 0x63, 0xa8, 0x23, 0x07, 0x86, 0xb3, 0x8d, 0xd4, 0x5f, 0xd1,
	0x04, 0xac, 0x57, 0x51, 0x72, 0x3a, 0x06, 0xb3, 0x2a, 0xf7, 0x93, 0xcc, 0xaa, 0x8c, 0xbe, 0x0d,
	0xf0, 0xe6, 0xb5, 0xd2, 0xcd, 0xb6, 0xd0, 0x95, 0xa8, 0x69, 0x0c, 0x56, 0x21, 0xca, 0xdd, 0xbf,
	0xc6, 0xe9, 0x79, 0x22, 0xf3, 0xa4, 0xd7, 0x4e, 0x32, 0x51, 0x72, 0xd6, 0x39, 0xe8, 0x04, 0x6c,
	0xb9, 0x6e, 0xd6, 0x1b, 0x15, 0x98, 0x21, 0x89, 0x5d, 0xb6, 0xaf, 0xba, 0x68, 0x38, 0x01, 0x63,
	0x8c, 0x58, 0xa7, 0xa3, 0x19, 0x58, 0xf8, 0x25, 0xb5, 0xc1, 0xcc, 0x96, 0xfe, 0x00, 0xdf, 0xc5,
	0xbb, 0x6f, 0xe0, 0xcb, 0x16, 0xbe, 0x49, 0x5d, 0x18, 0x2e, 0x9e, 0x9f, 0xe6, 0xcc, 0x27, 0x88,
	0x5e, 0x94, 0x6f, 0x51, 0x07, 0xc8, 0xb2, 0xaa, 0xfd, 0x21, 0xf6, 0xde, 0x6a, 0x94, 0x76, 0xf4,
	0x01, 0xa3, 0x5e, 0x18, 0x45, 0x6f, 0xc0, 0xab, 0xfe, 0xea, 0xc0, 0x08, 0x49, 0xec, 0xa5, 0x27,
	0x07, 0x99, 0x59, 0xdf, 0x43, 0x2f, 0x81, 0x14, 0xba, 0xed, 0xf6, 0xe6, 0xa5, 0x0e, 0x5a, 0x33,
	0xdd, 0x32, 0x64, 0xe9, 0x0a, 0x8e, 0x19, 0xdf, 0x08, 0xcd, 0x67, 0x2d, 0x2f, 0xb6, 0x9a, 0xd3,
	0x6b, 0x70, 0x7e, 0xe5, 0xe1, 0xd0, 0x2b, 0x17, 0xc1, 0x6e, 0xb5, 0x03, 0x1a, 0x82, 0xf3, 0x50,
	0x96, 0x4b, 0xce, 0x1b, 0x7a, 0x84, 0x1c, 0x37, 0xfd, 0xcf, 0xf1, 0x78, 0xb6, 0x3a, 0x4d, 0xa6,
	0xfd, 0x3b, 0xdf, 0xc9, 0x3c, 0xb7, 0xbb, 0x43, 0xdf, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xcf,
	0xb5, 0x95, 0x56, 0x01, 0x02, 0x00, 0x00,
}
