// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: consensus/rpc.proto

//option go_package = "icetrays/types/pb";

package consensus

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Instruction struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Params               []byte   `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Instruction) Reset()         { *m = Instruction{} }
func (m *Instruction) String() string { return proto.CompactTextString(m) }
func (*Instruction) ProtoMessage()    {}
func (*Instruction) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd3e6041543aef10, []int{0}
}
func (m *Instruction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instruction.Unmarshal(m, b)
}
func (m *Instruction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instruction.Marshal(b, m, deterministic)
}
func (m *Instruction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instruction.Merge(m, src)
}
func (m *Instruction) XXX_Size() int {
	return xxx_messageInfo_Instruction.Size(m)
}
func (m *Instruction) XXX_DiscardUnknown() {
	xxx_messageInfo_Instruction.DiscardUnknown(m)
}

var xxx_messageInfo_Instruction proto.InternalMessageInfo

func (m *Instruction) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Instruction) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

type Instructions struct {
	Instruction          []*Instruction `protobuf:"bytes,1,rep,name=instruction,proto3" json:"instruction,omitempty"`
	Ctx                  *Ctx           `protobuf:"bytes,2,opt,name=ctx,proto3" json:"ctx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Instructions) Reset()         { *m = Instructions{} }
func (m *Instructions) String() string { return proto.CompactTextString(m) }
func (*Instructions) ProtoMessage()    {}
func (*Instructions) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd3e6041543aef10, []int{1}
}
func (m *Instructions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instructions.Unmarshal(m, b)
}
func (m *Instructions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instructions.Marshal(b, m, deterministic)
}
func (m *Instructions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instructions.Merge(m, src)
}
func (m *Instructions) XXX_Size() int {
	return xxx_messageInfo_Instructions.Size(m)
}
func (m *Instructions) XXX_DiscardUnknown() {
	xxx_messageInfo_Instructions.DiscardUnknown(m)
}

var xxx_messageInfo_Instructions proto.InternalMessageInfo

func (m *Instructions) GetInstruction() []*Instruction {
	if m != nil {
		return m.Instruction
	}
	return nil
}

func (m *Instructions) GetCtx() *Ctx {
	if m != nil {
		return m.Ctx
	}
	return nil
}

type Ctx struct {
	Pre                  string   `protobuf:"bytes,1,opt,name=pre,proto3" json:"pre,omitempty"`
	Next                 string   `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ctx) Reset()         { *m = Ctx{} }
func (m *Ctx) String() string { return proto.CompactTextString(m) }
func (*Ctx) ProtoMessage()    {}
func (*Ctx) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd3e6041543aef10, []int{2}
}
func (m *Ctx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ctx.Unmarshal(m, b)
}
func (m *Ctx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ctx.Marshal(b, m, deterministic)
}
func (m *Ctx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ctx.Merge(m, src)
}
func (m *Ctx) XXX_Size() int {
	return xxx_messageInfo_Ctx.Size(m)
}
func (m *Ctx) XXX_DiscardUnknown() {
	xxx_messageInfo_Ctx.DiscardUnknown(m)
}

var xxx_messageInfo_Ctx proto.InternalMessageInfo

func (m *Ctx) GetPre() string {
	if m != nil {
		return m.Pre
	}
	return ""
}

func (m *Ctx) GetNext() string {
	if m != nil {
		return m.Next
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd3e6041543aef10, []int{3}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Instruction)(nil), "consensus.Instruction")
	proto.RegisterType((*Instructions)(nil), "consensus.Instructions")
	proto.RegisterType((*Ctx)(nil), "consensus.Ctx")
	proto.RegisterType((*Empty)(nil), "consensus.Empty")
}

func init() { proto.RegisterFile("consensus/rpc.proto", fileDescriptor_dd3e6041543aef10) }

var fileDescriptor_dd3e6041543aef10 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x8d, 0xd1, 0x96, 0x9d, 0xb4, 0x52, 0x46, 0x28, 0x8b, 0xa7, 0x90, 0xd3, 0x82, 0xb0,
	0xc2, 0x8a, 0xa0, 0xe7, 0x52, 0xc1, 0x6b, 0xfe, 0x41, 0x8d, 0x39, 0x54, 0xd8, 0x24, 0x24, 0xb3,
	0x10, 0xff, 0xbd, 0x6c, 0xd4, 0x9a, 0x4b, 0x6f, 0xdf, 0x4c, 0xde, 0x7b, 0x79, 0x0c, 0xdc, 0x1a,
	0xef, 0x92, 0x75, 0x69, 0x4a, 0x0f, 0x31, 0x98, 0x3e, 0x44, 0x4f, 0x1e, 0x9b, 0xd3, 0x52, 0xbd,
	0x80, 0x78, 0x73, 0x89, 0xe2, 0x64, 0xe8, 0xe8, 0x1d, 0x22, 0x5c, 0x19, 0xff, 0x61, 0x5b, 0x26,
	0x59, 0xb7, 0xd6, 0x85, 0x71, 0x0b, 0x8b, 0x70, 0x88, 0x87, 0x31, 0xb5, 0x97, 0x92, 0x75, 0x2b,
	0xfd, 0x3b, 0xa9, 0x4f, 0x58, 0x55, 0xd6, 0x84, 0xcf, 0x20, 0x8e, 0xff, 0x73, 0xcb, 0x24, 0xef,
	0xc4, 0xb0, 0xed, 0x4f, 0x7f, 0xf5, 0x95, 0x5a, 0xd7, 0x52, 0x94, 0xc0, 0x0d, 0xe5, 0x12, 0x2f,
	0x86, 0x9b, 0xca, 0xb1, 0xa3, 0xac, 0xe7, 0x27, 0x75, 0x0f, 0x7c, 0x47, 0x19, 0x37, 0xc0, 0x43,
	0xfc, 0x69, 0xd7, 0xe8, 0x19, 0xe7, 0xc2, 0xce, 0x66, 0x2a, 0xde, 0x46, 0x17, 0x56, 0x4b, 0xb8,
	0xde, 0x8f, 0x81, 0xbe, 0x86, 0x57, 0x58, 0x6b, 0x3b, 0x7a, 0xb2, 0xfb, 0x6c, 0xcd, 0x44, 0x16,
	0x9f, 0x60, 0xf9, 0x87, 0x67, 0x8a, 0xdd, 0x6d, 0xaa, 0x7d, 0x49, 0x51, 0x17, 0xef, 0x8b, 0x72,
	0xb6, 0xc7, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x16, 0x11, 0x6f, 0x6e, 0x4d, 0x01, 0x00, 0x00,
}
